env:
  global:
    - CONAN_USERNAME: "helmesjo"
    - CONAN_LOGIN_USERNAME: "helmesjo"
    - CONAN_CHANNEL: "stable"
    - CONAN_UPLOAD: "https://api.bintray.com/conan/helmesjo/public-conan"

linux: &linux
  os: linux
  dist: bionic
  language: python
  python: "3.7"
  services:
    - docker
osx: &osx
  os: osx
  language: generic
matrix:
  include:
     - <<: *linux
       env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8

install:
 - chmod +x .ci/install.sh
 - ./.ci/install.sh

script:
 - chmod +x .ci/run.sh
 - ./.ci/run.sh
