env:
   global:
     - CONAN_DOCKER_IMAGE: conanio/clang60
     - CONAN_LOGIN_USERNAME: helmesjo
     - #CONAN_PASSWORD: <specify-in-ci-server>
     - REMOTE_REPO: "https://api.bintray.com/conan/helmesjo/public-conan"

linux: &linux
   os: linux
   dist: bionic
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8
      - <<: *linux
        env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang70
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/clang9
      - <<: *osx
        osx_image: xcode10.3
        env: CONAN_APPLE_CLANG_VERSIONS=10.0
      - <<: *osx
        osx_image: xcode11.2
        env: CONAN_APPLE_CLANG_VERSIONS=11.0

script: >
  mkdir build &&
  cd build &&
  cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON .. &&
  cmake --build . &&
  ctest &&
  cd .. &&
  pip install conan --upgrade &&
  conan create . helmesjo/stable &&
  conan remote add repo $REMOTE_REPO &&
  conan upload "*" -r repo --confirm
